### ISSUE TITLE
heroku docker workflow changed. No docs?

### ISSUE THREAD

**Issue by nilnullzip** [heroku/heroku-docker#114]
FYI: This morning we found our previous heroku docker:release would no longer work. It was asking for app.json.

We found no documentation on Heroku for this change. We came to this repository to see what happened. It seems there is a new workflow involving app.json and docker-compose.yml.

**Comment by friism** [comment]
@nilnullzip yes, sorry about that. We're rolling stuff out for a release tmrw (Tuesday). I just pushed the docs actually: devcenter.heroku.com/articles/docker

I'm really sorry that this change broke your workflow, but I also want to stress that the Docker features are in beta.

If you want, please reach out to friis@heroku.com with details of your use case so that we can better support it and keep things stable for you in the future.

Michael

**Comment by nilnullzip** [comment]
Hey Michael, Thanks for the update! We love this project and understand it's in beta. Just wanted to make sure the project knew that this was pushed live. Thanks for all the good work! -Juan

**Comment by hunterloftis** [comment]
@nilnullzip thanks for bringing this up; we should have communicated the change sooner. We'll send a notice out to existing users so others won't be surprised. I'm sorry for the interruption and I hope you will give v1.0.0 a shot.

Also, @friism, we should document alpha => 1.0.0 migration instructions. It should be relatively simple to continue deploying with the latest version of heroku-docker. Something like:

#### Create an `app.json` with at least an 'image', eg:

```js
{
  "image": "heroku/nodejs"
}
```

#### Ensure that you have a `Procfile`, eg:

```
web: node server.js
```

#### Ensure that you have Docker-Compose installed

```
$ docker-compose -v
```

#### Create a Dockerfile and a docker-compose.yml

```
$ heroku docker:init
```

#### Run the app locally

```
$ docker-compose up web
```

#### Release the app

```
$ heroku docker:release
```

**Comment by nilnullzip** [comment]
One other problem we noticed in moving our node project over to the new flow. When the process starts on heroku, it does a "cd /app/user" before running node as we specified. I have no idea where it's getting that /app/user because it's not specified anywhere in the dockerfile or the docker-compse.yml.

**Comment by hunterloftis** [comment]
All of the code in your project's directory (let's say `myproject`) is, with the traditional buildpack pipeline, built into `/app` on Heroku. However, to be able to optionally mount `myproject` as a volume without blowing away other important bits of the container (like the node binary), that must also live in `/app`, user files are moved one level deeper into `/app/user`.

So `myproject/server.js` will end up, on `:release`, being put into `/app/user/server.js`. Since the Heroku runtime uses `/app` as the working directory, `:release` prepends `cd /app/user &&` so relative paths will still work.

Are you seeing issues where those paths don't line up correctly?

**Comment by nilnullzip** [comment]
Our previous dockerfile did not use /app/user. The glitch we ran into was the "cd /app/user/" was failing because that directory did not exist.

**Comment by hunterloftis** [comment]
Ah I see, so an image was created with the previous alpha version, and then when `:release` ran with 1.0.0 that sneakily self-updated on you, it tried to cd into a directory that didn't exist?

When an image is created with the latest version, `/app/user` should be created automatically:

- https://github.com/heroku/docker-nodejs/blob/master/Dockerfile#L21
