### ISSUE TITLE
Apache Commons Damon (jsvc) and Heroku/Docker

### ISSUE THREAD

**Issue by arichiardi** [heroku/heroku-docker#93]
Hi all,

I would like to ask here if  there is already some plan about supporting ```jsvc``` apps in the heroku/docker plugin. This would be greatly useful for cross-jvm apps.

Maybe this is not the correct place to ask, in which case please suggest some other resource/Dockerfile where I can get inspired from and then I will contribute my work here as well ok? 

:+1:

**Comment by hunterloftis** [comment]
Thanks for asking! I'll pass that question over to our JVM maintainer, @jkutner

**Comment by ojacobson** [comment]
The big issue is that `jsvc` implements "classic" or "SysV" daemonization, where each service application is responsible for detaching itself from the starting process (usually your shell session, sometimes sysv init) and attaching to PID 1, so that the service runs "in the background". Classic daemonization, regardless of platform, is tricky to get right, and duplicating all of that code across every service has lead to a lot of fragmentation and a lot of buggy daemons. The container ecosystem, as well as several Linux distributions, are moving away from SysV daemonization towards a model where the daemon management logic is more centralized and service applications _do not_ manage it for themselves.

Both Docker and Heroku follow the new model, and assume that when a process exits, the associated service is no longer running and that it's time to tear the container down. Classic daemons, including `jsvc` services, don't satisfy that model: they start a new process to run the actual daemon, and then allow the initiating process to exit so that the daemon runs in the background.

As a workaround for `jsvc` specifically, you can use the `-nodetach` option to prevent `jsvc` from exiting once the service has started. Longer-term, the right approach is to use the normal `java` launcher, without daemonization helpers, when working with containers. This'll work in Docker or in Heroku, as well as when writing native daemons with `upstart` (Ubuntu) or `systemd` (Debian).

For some background reading, have a look at [this](http://www.freedesktop.org/software/systemd/man/daemon.html) article and [this](http://grimoire.ca/devops/self-daemonization-sucks) article.

Let me know if that helps! -o

**Comment by arichiardi** [comment]
Yes, it helps, and thanks for your answer :+1: Now I don't know where to put my ```stop``` code but that's okay.

**Comment by xuedihualu** [comment]
@arichiardi
hi，I have the same problem. JSVC can't be running in the container,Can you tell me how to solve it

**Comment by arichiardi** [comment]
@xuedihualu I have not tried the above solution yet, as soon as I do it I will report here ok?
